package com.bignerdranch.testphilosophyjava.homecontrol.test3;

public enum Watercolors {
    A_ZINC, B_LEMOM_YELLOW,C_MEDIUM_YELLOW, D_DEEP_YELLOW, E_ORANGE,
    F_BRILLIANT_RED, G_CRIMSON, H_MAGENTA,I_ROSE_MADDER, J_VIOLET,
    K_CERULLEAN_BLUE_HUE, L_PHTHALO_BLUE, M_ULTRAMARINE,
    N_CABALT_BLUE_HUE, O_PERMANENT_GREEN, P_VIRIDIAN_HUE,
    Q_SAP_GREEN, R_YELLOW_ORCHRE, S_BURNT_SIENNA, T_RAW_UMBER,
    U_BURNT_UMBER, W_PAYNES_GRAY, X_IVORY_BLACK
}
